### ISSUE TITLE
Pressing R on an underground belt does not reverse it

### ISSUE THREAD

**Issue by mkaito** [Nexela/PickerExtended#65] opened 2017-12-15 21:49 UTC
Factorio 0.16.3
PE 3.0.1

Pressing R on a piece of belt or an inserter reverses it, but doing the same on an underground belt does not.

**Comment by staviq** [comment] 2017-12-16 02:42
Temorary workaround i found: shift+r seems to work correctly, except it rotates in the reverse direction.

**Comment by Nexela** [comment] 2017-12-16 03:32
Duplicate of #61

**Closed by Nexela** 2017-12-16 03:32 UTC
Labels: duplicate
